window.CONTAINER_LED_TELAS = Object.freeze([
  Object.freeze({
    id: 1,
    slug: "rondon-pacheco",
    nome: "Rondon Pacheco",
    endereco: "Av. Rondon Pacheco, 2064",
    bairro: "Vigilato Pereira",
    cidade: "Uberlândia",
    estado: "MG",
    largura: 3,
    altura: 6,
    status: "Em operação",
    imagem: "/assets/painel-rondon.webp",
    imagemAlt: "Tela digital Container LED na Avenida Rondon Pacheco",
    googleMaps: "https://www.google.com/maps/search/?api=1&query=Av.%20Rondon%20Pacheco%2C%202064%2C%20Uberl%C3%A2ndia%2C%20MG",
    mapaEmbed: "https://www.google.com/maps?q=Av.%20Rondon%20Pacheco%2C%202064%2C%20Uberl%C3%A2ndia%2C%20MG&output=embed",
    audiencia: "9,2 mi/mês",
    insercoes: "~360/dia",
    resolucao: "1080×1920 · 9:16 · STORIES",
    descricao: "Na principal avenida de Uberlândia, ao lado do Colégio Gabarito e Griff Shopping, com amplo campo visual e fluxo intenso."
  }),
  Object.freeze({
    id: 2,
    slug: "anselmo-alves",
    nome: "Anselmo Alves dos Santos — Pátio Sabiá",
    endereco: "Av. Anselmo Alves dos Santos, 1056",
    bairro: "Santa Mônica",
    cidade: "Uberlândia",
    estado: "MG",
    largura: 4,
    altura: 2,
    status: "Em operação",
    imagem: "/assets/painel-anselmo-alves.webp",
    imagemAlt: "Tela digital Container LED na Avenida Anselmo Alves dos Santos em frente ao Pátio Sabiá",
    googleMaps: "https://www.google.com/maps/search/?api=1&query=Av.%20Anselmo%20Alves%20dos%20Santos%2C%201056%2C%20Uberl%C3%A2ndia%2C%20MG",
    mapaEmbed: "https://www.google.com/maps?q=Av.%20Anselmo%20Alves%20dos%20Santos%2C%201056%2C%20Uberl%C3%A2ndia%2C%20MG&z=13&output=embed",
    audiencia: "4,65 mi/mês",
    insercoes: "~360/dia",
    resolucao: "1080×1920 · 9:16 · STORIES",
    descricao: "Em frente ao Pátio Sabiá, em uma região de alto fluxo que conecta importantes setores de Uberlândia, a 200 metros do Parque do Sabiá."
  }),
  Object.freeze({
    id: 3,
    slug: "getulio-vargas",
    nome: "Getúlio Vargas",
    endereco: "",
    bairro: "",
    cidade: "Uberlândia",
    estado: "MG",
    largura: null,
    altura: null,
    status: "Em construção",
    imagem: "",
    imagemAlt: "",
    googleMaps: "",
    mapaEmbed: "",
    audiencia: "",
    insercoes: "",
    resolucao: "",
    descricao: ""
  })
]);